services:
  db:
    image: postgres:16-alpine
    container_name: db_pos
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -h 127.0.0.1 -p 5432"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  migrate:
    image: axoncompany/pos_migrate:v1
    container_name: pos_migrate
    depends_on:
      db:
        condition: service_healthy
    entrypoint:
      - migrate
      - -path=/migrations
      - -database
      - postgres://${DB_USER}:${DB_PASSWORD}@${MIGRATE_HOST:-db}:${MIGRATE_PORT:-5432}/${DB_NAME}?sslmode=${DB_SSLMODE:-disable}
    command: ["up"]
    restart: "no"

  app:
    image: axoncompany/pos_axon:v1
    container_name: pos_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      APP_ENV: dev
      HTTP_HOST: 0.0.0.0
      HTTP_PORT: "8080"
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_SSLMODE: disable
    ports:
      - "8080:8080"
    restart: unless-stopped


volumes:
  db_data: